--------------------------------------------------------------------------------
-- This script creates tables to populate the database schema and then inserts
-- test data into the database to support the tests
--------------------------------------------------------------------------------

CREATE TABLE movies (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(100) NOT NULL,
  year_of_release INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO movies (name, year_of_release, created_at) VALUES
    ('Gone With The Wind', 1939, '2024-10-10 10:10:10'),
    ('Back To The Future', 1985, '2024-10-10 10:10:10');
